## Q1: Don't type

Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [2]:
import numpy as np
arr = np.arange(1,16).reshape(3,5).T
print(arr)

arr2 = np.concatenate((arr[1],arr[3])).reshape(2,3)
print(arr2)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]


## Q2: Edges

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [3]:
import numpy as np
n_row=4
n_col=5
A=np.ones((n_row,n_col) ,dtype=int)
A[1:n_row-1,1:n_col-1]=0
print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Q3: Histograms

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [5]:
import numpy as np
sample=np.loadtxt("sample.txt")
#print(sample[:,1])
counts,edges=np.histogram(sample[:,1])
bin_size=edges[1]-edges[0]
bincenter=np.array(edges[:-1]+bin_size/2)
print("bin centers:",bincenter)
print("bin counts:",counts)

bin centers: [-27.12926257 -20.21093194 -13.29260131  -6.37427068   0.54405995
   7.46239059  14.38072122  21.29905185  28.21738248  35.13571311]
bin counts: [ 3  4  9 22 22 22  9  7  1  1]


## Q6: Game of life 
run game_of_life.py file